-- Seed sample units into public.units.
-- Run this only after the units table and optional pitch/detail columns exist.

INSERT INTO public.units (
  user_id,
  name,
  code,
  location_type,
  shape_type,
  color,
  mark_number,
  bars,
  spacing_mm,
  pitch_mm,
  description,
  is_active,
  template_id
)
VALUES
(
  (SELECT id FROM auth.users ORDER BY created_at ASC LIMIT 1),
  'Outer straight',
  'red-1',
  '外周部',
  'straight',
  'red',
  1,
  '[{"diameter":"D13","qtyPerUnit":4},{"diameter":"D10","qtyPerUnit":1}]'::jsonb,
  200,
  200,
  NULL,
  TRUE,
  'outer_straight'
),
(
  (SELECT id FROM auth.users ORDER BY created_at ASC LIMIT 1),
  'Inner straight',
  'blue-1',
  '内部',
  'straight',
  'blue',
  1,
  '[{"diameter":"D13","qtyPerUnit":2},{"diameter":"D10","qtyPerUnit":1}]'::jsonb,
  200,
  200,
  NULL,
  TRUE,
  'inner_straight'
),
(
  (SELECT id FROM auth.users ORDER BY created_at ASC LIMIT 1),
  'Outer corner out',
  'red-2',
  '外周部',
  'corner_out',
  'red',
  2,
  '[{"diameter":"D13","qtyPerUnit":3},{"diameter":"D10","qtyPerUnit":1}]'::jsonb,
  NULL,
  NULL,
  NULL,
  TRUE,
  'outer_corner_out'
),
(
  (SELECT id FROM auth.users ORDER BY created_at ASC LIMIT 1),
  'Inner T',
  'blue-4',
  '内部',
  'corner_T',
  'blue',
  4,
  '[{"diameter":"D13","qtyPerUnit":2},{"diameter":"D10","qtyPerUnit":1}]'::jsonb,
  NULL,
  NULL,
  NULL,
  TRUE,
  'inner_T'
),
(
  (SELECT id FROM auth.users ORDER BY created_at ASC LIMIT 1),
  'Base straight',
  'emerald-1',
  'ベース',
  'straight',
  'emerald',
  1,
  '[{"diameter":"D13","qtyPerUnit":3},{"diameter":"D10","qtyPerUnit":2}]'::jsonb,
  150,
  150,
  NULL,
  TRUE,
  'base_standard'
),
(
  (SELECT id FROM auth.users ORDER BY created_at ASC LIMIT 1),
  'Opening reinforce',
  'violet-1',
  'その他',
  'opening',
  'violet',
  1,
  '[{"diameter":"D13","qtyPerUnit":2}]'::jsonb,
  NULL,
  NULL,
  'Opening reinforcement sample',
  FALSE,
  'opening_reinforce'
);
